// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: edgeorchestra/v1/common.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

public enum Edgeorchestra_V1_DeviceStatus: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case online // = 1
  case offline // = 2
  case training // = 3
  case error // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .online
    case 2: self = .offline
    case 3: self = .training
    case 4: self = .error
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .online: return 1
    case .offline: return 2
    case .training: return 3
    case .error: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Edgeorchestra_V1_DeviceStatus] = [
    .unspecified,
    .online,
    .offline,
    .training,
    .error,
  ]

}

public enum Edgeorchestra_V1_BatteryState: SwiftProtobuf.Enum, Swift.CaseIterable {
  public typealias RawValue = Int
  case unspecified // = 0
  case charging // = 1
  case discharging // = 2
  case full // = 3
  case notCharging // = 4
  case UNRECOGNIZED(Int)

  public init() {
    self = .unspecified
  }

  public init?(rawValue: Int) {
    switch rawValue {
    case 0: self = .unspecified
    case 1: self = .charging
    case 2: self = .discharging
    case 3: self = .full
    case 4: self = .notCharging
    default: self = .UNRECOGNIZED(rawValue)
    }
  }

  public var rawValue: Int {
    switch self {
    case .unspecified: return 0
    case .charging: return 1
    case .discharging: return 2
    case .full: return 3
    case .notCharging: return 4
    case .UNRECOGNIZED(let i): return i
    }
  }

  // The compiler won't synthesize support with the UNRECOGNIZED case.
  public static let allCases: [Edgeorchestra_V1_BatteryState] = [
    .unspecified,
    .charging,
    .discharging,
    .full,
    .notCharging,
  ]

}

public struct Edgeorchestra_V1_DeviceId: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var value: String = String()

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Edgeorchestra_V1_BatteryInfo: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0.0 to 1.0
  public var level: Float = 0

  public var state: Edgeorchestra_V1_BatteryState = .unspecified

  public var isLowPowerMode: Bool = false

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Edgeorchestra_V1_DeviceCapabilities: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// e.g. "Apple M1", "A15 Bionic"
  public var chip: String = String()

  public var memoryBytes: UInt64 = 0

  public var cpuCores: UInt32 = 0

  public var gpuCores: UInt32 = 0

  public var neuralEngineCores: UInt32 = 0

  /// e.g. ["coreml", "mlx"]
  public var supportedFrameworks: [String] = []

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}
}

public struct Edgeorchestra_V1_DeviceMetrics: Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  /// 0.0 to 1.0
  public var cpuUsage: Float = 0

  /// 0.0 to 1.0
  public var memoryUsage: Float = 0

  /// 0.0 to 1.0
  public var thermalPressure: Float = 0

  public var battery: Edgeorchestra_V1_BatteryInfo {
    get {_battery ?? Edgeorchestra_V1_BatteryInfo()}
    set {_battery = newValue}
  }
  /// Returns true if `battery` has been explicitly set.
  public var hasBattery: Bool {self._battery != nil}
  /// Clears the value of `battery`. Subsequent reads from it will return its default value.
  public mutating func clearBattery() {self._battery = nil}

  public var collectedAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_collectedAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_collectedAt = newValue}
  }
  /// Returns true if `collectedAt` has been explicitly set.
  public var hasCollectedAt: Bool {self._collectedAt != nil}
  /// Clears the value of `collectedAt`. Subsequent reads from it will return its default value.
  public mutating func clearCollectedAt() {self._collectedAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _battery: Edgeorchestra_V1_BatteryInfo? = nil
  fileprivate var _collectedAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
}

public struct Edgeorchestra_V1_DeviceInfo: @unchecked Sendable {
  // SwiftProtobuf.Message conformance is added in an extension below. See the
  // `Message` and `Message+*Additions` files in the SwiftProtobuf library for
  // methods supported on all messages.

  public var id: Edgeorchestra_V1_DeviceId {
    get {_storage._id ?? Edgeorchestra_V1_DeviceId()}
    set {_uniqueStorage()._id = newValue}
  }
  /// Returns true if `id` has been explicitly set.
  public var hasID: Bool {_storage._id != nil}
  /// Clears the value of `id`. Subsequent reads from it will return its default value.
  public mutating func clearID() {_uniqueStorage()._id = nil}

  public var name: String {
    get {_storage._name}
    set {_uniqueStorage()._name = newValue}
  }

  /// e.g. "iPhone 14 Pro", "MacBook Pro"
  public var deviceModel: String {
    get {_storage._deviceModel}
    set {_uniqueStorage()._deviceModel = newValue}
  }

  public var osVersion: String {
    get {_storage._osVersion}
    set {_uniqueStorage()._osVersion = newValue}
  }

  public var capabilities: Edgeorchestra_V1_DeviceCapabilities {
    get {_storage._capabilities ?? Edgeorchestra_V1_DeviceCapabilities()}
    set {_uniqueStorage()._capabilities = newValue}
  }
  /// Returns true if `capabilities` has been explicitly set.
  public var hasCapabilities: Bool {_storage._capabilities != nil}
  /// Clears the value of `capabilities`. Subsequent reads from it will return its default value.
  public mutating func clearCapabilities() {_uniqueStorage()._capabilities = nil}

  public var status: Edgeorchestra_V1_DeviceStatus {
    get {_storage._status}
    set {_uniqueStorage()._status = newValue}
  }

  public var latestMetrics: Edgeorchestra_V1_DeviceMetrics {
    get {_storage._latestMetrics ?? Edgeorchestra_V1_DeviceMetrics()}
    set {_uniqueStorage()._latestMetrics = newValue}
  }
  /// Returns true if `latestMetrics` has been explicitly set.
  public var hasLatestMetrics: Bool {_storage._latestMetrics != nil}
  /// Clears the value of `latestMetrics`. Subsequent reads from it will return its default value.
  public mutating func clearLatestMetrics() {_uniqueStorage()._latestMetrics = nil}

  public var registeredAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._registeredAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._registeredAt = newValue}
  }
  /// Returns true if `registeredAt` has been explicitly set.
  public var hasRegisteredAt: Bool {_storage._registeredAt != nil}
  /// Clears the value of `registeredAt`. Subsequent reads from it will return its default value.
  public mutating func clearRegisteredAt() {_uniqueStorage()._registeredAt = nil}

  public var lastSeenAt: SwiftProtobuf.Google_Protobuf_Timestamp {
    get {_storage._lastSeenAt ?? SwiftProtobuf.Google_Protobuf_Timestamp()}
    set {_uniqueStorage()._lastSeenAt = newValue}
  }
  /// Returns true if `lastSeenAt` has been explicitly set.
  public var hasLastSeenAt: Bool {_storage._lastSeenAt != nil}
  /// Clears the value of `lastSeenAt`. Subsequent reads from it will return its default value.
  public mutating func clearLastSeenAt() {_uniqueStorage()._lastSeenAt = nil}

  public var unknownFields = SwiftProtobuf.UnknownStorage()

  public init() {}

  fileprivate var _storage = _StorageClass.defaultInstance
}

// MARK: - Code below here is support for the SwiftProtobuf runtime.

fileprivate let _protobuf_package = "edgeorchestra.v1"

extension Edgeorchestra_V1_DeviceStatus: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0DEVICE_STATUS_UNSPECIFIED\0\u{1}DEVICE_STATUS_ONLINE\0\u{1}DEVICE_STATUS_OFFLINE\0\u{1}DEVICE_STATUS_TRAINING\0\u{1}DEVICE_STATUS_ERROR\0")
}

extension Edgeorchestra_V1_BatteryState: SwiftProtobuf._ProtoNameProviding {
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{2}\0BATTERY_STATE_UNSPECIFIED\0\u{1}BATTERY_STATE_CHARGING\0\u{1}BATTERY_STATE_DISCHARGING\0\u{1}BATTERY_STATE_FULL\0\u{1}BATTERY_STATE_NOT_CHARGING\0")
}

extension Edgeorchestra_V1_DeviceId: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceId"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}value\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.value) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.value.isEmpty {
      try visitor.visitSingularStringField(value: self.value, fieldNumber: 1)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Edgeorchestra_V1_DeviceId, rhs: Edgeorchestra_V1_DeviceId) -> Bool {
    if lhs.value != rhs.value {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Edgeorchestra_V1_BatteryInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".BatteryInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}level\0\u{1}state\0\u{3}is_low_power_mode\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.level) }()
      case 2: try { try decoder.decodeSingularEnumField(value: &self.state) }()
      case 3: try { try decoder.decodeSingularBoolField(value: &self.isLowPowerMode) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if self.level.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.level, fieldNumber: 1)
    }
    if self.state != .unspecified {
      try visitor.visitSingularEnumField(value: self.state, fieldNumber: 2)
    }
    if self.isLowPowerMode != false {
      try visitor.visitSingularBoolField(value: self.isLowPowerMode, fieldNumber: 3)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Edgeorchestra_V1_BatteryInfo, rhs: Edgeorchestra_V1_BatteryInfo) -> Bool {
    if lhs.level != rhs.level {return false}
    if lhs.state != rhs.state {return false}
    if lhs.isLowPowerMode != rhs.isLowPowerMode {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Edgeorchestra_V1_DeviceCapabilities: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceCapabilities"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}chip\0\u{3}memory_bytes\0\u{3}cpu_cores\0\u{3}gpu_cores\0\u{3}neural_engine_cores\0\u{3}supported_frameworks\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularStringField(value: &self.chip) }()
      case 2: try { try decoder.decodeSingularUInt64Field(value: &self.memoryBytes) }()
      case 3: try { try decoder.decodeSingularUInt32Field(value: &self.cpuCores) }()
      case 4: try { try decoder.decodeSingularUInt32Field(value: &self.gpuCores) }()
      case 5: try { try decoder.decodeSingularUInt32Field(value: &self.neuralEngineCores) }()
      case 6: try { try decoder.decodeRepeatedStringField(value: &self.supportedFrameworks) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    if !self.chip.isEmpty {
      try visitor.visitSingularStringField(value: self.chip, fieldNumber: 1)
    }
    if self.memoryBytes != 0 {
      try visitor.visitSingularUInt64Field(value: self.memoryBytes, fieldNumber: 2)
    }
    if self.cpuCores != 0 {
      try visitor.visitSingularUInt32Field(value: self.cpuCores, fieldNumber: 3)
    }
    if self.gpuCores != 0 {
      try visitor.visitSingularUInt32Field(value: self.gpuCores, fieldNumber: 4)
    }
    if self.neuralEngineCores != 0 {
      try visitor.visitSingularUInt32Field(value: self.neuralEngineCores, fieldNumber: 5)
    }
    if !self.supportedFrameworks.isEmpty {
      try visitor.visitRepeatedStringField(value: self.supportedFrameworks, fieldNumber: 6)
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Edgeorchestra_V1_DeviceCapabilities, rhs: Edgeorchestra_V1_DeviceCapabilities) -> Bool {
    if lhs.chip != rhs.chip {return false}
    if lhs.memoryBytes != rhs.memoryBytes {return false}
    if lhs.cpuCores != rhs.cpuCores {return false}
    if lhs.gpuCores != rhs.gpuCores {return false}
    if lhs.neuralEngineCores != rhs.neuralEngineCores {return false}
    if lhs.supportedFrameworks != rhs.supportedFrameworks {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Edgeorchestra_V1_DeviceMetrics: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceMetrics"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{3}cpu_usage\0\u{3}memory_usage\0\u{3}thermal_pressure\0\u{1}battery\0\u{3}collected_at\0")

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    while let fieldNumber = try decoder.nextFieldNumber() {
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every case branch when no optimizations are
      // enabled. https://github.com/apple/swift-protobuf/issues/1034
      switch fieldNumber {
      case 1: try { try decoder.decodeSingularFloatField(value: &self.cpuUsage) }()
      case 2: try { try decoder.decodeSingularFloatField(value: &self.memoryUsage) }()
      case 3: try { try decoder.decodeSingularFloatField(value: &self.thermalPressure) }()
      case 4: try { try decoder.decodeSingularMessageField(value: &self._battery) }()
      case 5: try { try decoder.decodeSingularMessageField(value: &self._collectedAt) }()
      default: break
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    // The use of inline closures is to circumvent an issue where the compiler
    // allocates stack space for every if/case branch local when no optimizations
    // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
    // https://github.com/apple/swift-protobuf/issues/1182
    if self.cpuUsage.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.cpuUsage, fieldNumber: 1)
    }
    if self.memoryUsage.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.memoryUsage, fieldNumber: 2)
    }
    if self.thermalPressure.bitPattern != 0 {
      try visitor.visitSingularFloatField(value: self.thermalPressure, fieldNumber: 3)
    }
    try { if let v = self._battery {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 4)
    } }()
    try { if let v = self._collectedAt {
      try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
    } }()
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Edgeorchestra_V1_DeviceMetrics, rhs: Edgeorchestra_V1_DeviceMetrics) -> Bool {
    if lhs.cpuUsage != rhs.cpuUsage {return false}
    if lhs.memoryUsage != rhs.memoryUsage {return false}
    if lhs.thermalPressure != rhs.thermalPressure {return false}
    if lhs._battery != rhs._battery {return false}
    if lhs._collectedAt != rhs._collectedAt {return false}
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}

extension Edgeorchestra_V1_DeviceInfo: SwiftProtobuf.Message, SwiftProtobuf._MessageImplementationBase, SwiftProtobuf._ProtoNameProviding {
  public static let protoMessageName: String = _protobuf_package + ".DeviceInfo"
  public static let _protobuf_nameMap = SwiftProtobuf._NameMap(bytecode: "\0\u{1}id\0\u{1}name\0\u{3}device_model\0\u{3}os_version\0\u{1}capabilities\0\u{1}status\0\u{3}latest_metrics\0\u{3}registered_at\0\u{3}last_seen_at\0")

  fileprivate class _StorageClass {
    var _id: Edgeorchestra_V1_DeviceId? = nil
    var _name: String = String()
    var _deviceModel: String = String()
    var _osVersion: String = String()
    var _capabilities: Edgeorchestra_V1_DeviceCapabilities? = nil
    var _status: Edgeorchestra_V1_DeviceStatus = .unspecified
    var _latestMetrics: Edgeorchestra_V1_DeviceMetrics? = nil
    var _registeredAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil
    var _lastSeenAt: SwiftProtobuf.Google_Protobuf_Timestamp? = nil

      // This property is used as the initial default value for new instances of the type.
      // The type itself is protecting the reference to its storage via CoW semantics.
      // This will force a copy to be made of this reference when the first mutation occurs;
      // hence, it is safe to mark this as `nonisolated(unsafe)`.
      static nonisolated(unsafe) let defaultInstance = _StorageClass()

    private init() {}

    init(copying source: _StorageClass) {
      _id = source._id
      _name = source._name
      _deviceModel = source._deviceModel
      _osVersion = source._osVersion
      _capabilities = source._capabilities
      _status = source._status
      _latestMetrics = source._latestMetrics
      _registeredAt = source._registeredAt
      _lastSeenAt = source._lastSeenAt
    }
  }

  fileprivate mutating func _uniqueStorage() -> _StorageClass {
    if !isKnownUniquelyReferenced(&_storage) {
      _storage = _StorageClass(copying: _storage)
    }
    return _storage
  }

  public mutating func decodeMessage<D: SwiftProtobuf.Decoder>(decoder: inout D) throws {
    _ = _uniqueStorage()
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      while let fieldNumber = try decoder.nextFieldNumber() {
        // The use of inline closures is to circumvent an issue where the compiler
        // allocates stack space for every case branch when no optimizations are
        // enabled. https://github.com/apple/swift-protobuf/issues/1034
        switch fieldNumber {
        case 1: try { try decoder.decodeSingularMessageField(value: &_storage._id) }()
        case 2: try { try decoder.decodeSingularStringField(value: &_storage._name) }()
        case 3: try { try decoder.decodeSingularStringField(value: &_storage._deviceModel) }()
        case 4: try { try decoder.decodeSingularStringField(value: &_storage._osVersion) }()
        case 5: try { try decoder.decodeSingularMessageField(value: &_storage._capabilities) }()
        case 6: try { try decoder.decodeSingularEnumField(value: &_storage._status) }()
        case 7: try { try decoder.decodeSingularMessageField(value: &_storage._latestMetrics) }()
        case 8: try { try decoder.decodeSingularMessageField(value: &_storage._registeredAt) }()
        case 9: try { try decoder.decodeSingularMessageField(value: &_storage._lastSeenAt) }()
        default: break
        }
      }
    }
  }

  public func traverse<V: SwiftProtobuf.Visitor>(visitor: inout V) throws {
    try withExtendedLifetime(_storage) { (_storage: _StorageClass) in
      // The use of inline closures is to circumvent an issue where the compiler
      // allocates stack space for every if/case branch local when no optimizations
      // are enabled. https://github.com/apple/swift-protobuf/issues/1034 and
      // https://github.com/apple/swift-protobuf/issues/1182
      try { if let v = _storage._id {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 1)
      } }()
      if !_storage._name.isEmpty {
        try visitor.visitSingularStringField(value: _storage._name, fieldNumber: 2)
      }
      if !_storage._deviceModel.isEmpty {
        try visitor.visitSingularStringField(value: _storage._deviceModel, fieldNumber: 3)
      }
      if !_storage._osVersion.isEmpty {
        try visitor.visitSingularStringField(value: _storage._osVersion, fieldNumber: 4)
      }
      try { if let v = _storage._capabilities {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 5)
      } }()
      if _storage._status != .unspecified {
        try visitor.visitSingularEnumField(value: _storage._status, fieldNumber: 6)
      }
      try { if let v = _storage._latestMetrics {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 7)
      } }()
      try { if let v = _storage._registeredAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 8)
      } }()
      try { if let v = _storage._lastSeenAt {
        try visitor.visitSingularMessageField(value: v, fieldNumber: 9)
      } }()
    }
    try unknownFields.traverse(visitor: &visitor)
  }

  public static func ==(lhs: Edgeorchestra_V1_DeviceInfo, rhs: Edgeorchestra_V1_DeviceInfo) -> Bool {
    if lhs._storage !== rhs._storage {
      let storagesAreEqual: Bool = withExtendedLifetime((lhs._storage, rhs._storage)) { (_args: (_StorageClass, _StorageClass)) in
        let _storage = _args.0
        let rhs_storage = _args.1
        if _storage._id != rhs_storage._id {return false}
        if _storage._name != rhs_storage._name {return false}
        if _storage._deviceModel != rhs_storage._deviceModel {return false}
        if _storage._osVersion != rhs_storage._osVersion {return false}
        if _storage._capabilities != rhs_storage._capabilities {return false}
        if _storage._status != rhs_storage._status {return false}
        if _storage._latestMetrics != rhs_storage._latestMetrics {return false}
        if _storage._registeredAt != rhs_storage._registeredAt {return false}
        if _storage._lastSeenAt != rhs_storage._lastSeenAt {return false}
        return true
      }
      if !storagesAreEqual {return false}
    }
    if lhs.unknownFields != rhs.unknownFields {return false}
    return true
  }
}
