// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: edgeorchestra/v1/device.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - edgeorchestra.v1.DeviceRegistry

/// Namespace containing generated types for the "edgeorchestra.v1.DeviceRegistry" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Edgeorchestra_V1_DeviceRegistry: Sendable {
    /// Service descriptor for the "edgeorchestra.v1.DeviceRegistry" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.DeviceRegistry")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Register" metadata.
        public enum Register: Sendable {
            /// Request type for "Register".
            public typealias Input = Edgeorchestra_V1_RegisterRequest
            /// Response type for "Register".
            public typealias Output = Edgeorchestra_V1_RegisterResponse
            /// Descriptor for "Register".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.DeviceRegistry"),
                method: "Register"
            )
        }
        /// Namespace for "Unregister" metadata.
        public enum Unregister: Sendable {
            /// Request type for "Unregister".
            public typealias Input = Edgeorchestra_V1_UnregisterRequest
            /// Response type for "Unregister".
            public typealias Output = Edgeorchestra_V1_UnregisterResponse
            /// Descriptor for "Unregister".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.DeviceRegistry"),
                method: "Unregister"
            )
        }
        /// Namespace for "ListDevices" metadata.
        public enum ListDevices: Sendable {
            /// Request type for "ListDevices".
            public typealias Input = Edgeorchestra_V1_ListDevicesRequest
            /// Response type for "ListDevices".
            public typealias Output = Edgeorchestra_V1_ListDevicesResponse
            /// Descriptor for "ListDevices".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.DeviceRegistry"),
                method: "ListDevices"
            )
        }
        /// Namespace for "GetDevice" metadata.
        public enum GetDevice: Sendable {
            /// Request type for "GetDevice".
            public typealias Input = Edgeorchestra_V1_GetDeviceRequest
            /// Response type for "GetDevice".
            public typealias Output = Edgeorchestra_V1_GetDeviceResponse
            /// Descriptor for "GetDevice".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.DeviceRegistry"),
                method: "GetDevice"
            )
        }
        /// Descriptors for all methods in the "edgeorchestra.v1.DeviceRegistry" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Register.descriptor,
            Unregister.descriptor,
            ListDevices.descriptor,
            GetDevice.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "edgeorchestra.v1.DeviceRegistry" service.
    public static let edgeorchestra_v1_DeviceRegistry = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.DeviceRegistry")
}

// MARK: edgeorchestra.v1.DeviceRegistry (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_DeviceRegistry {
    /// Generated client protocol for the "edgeorchestra.v1.DeviceRegistry" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Register" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_RegisterRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_RegisterRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_RegisterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func register<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_RegisterRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_RegisterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_RegisterResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_RegisterResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "Unregister" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_UnregisterRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_UnregisterRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_UnregisterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func unregister<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_UnregisterRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_UnregisterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_UnregisterResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UnregisterResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "ListDevices" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_ListDevicesRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_ListDevicesRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_ListDevicesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func listDevices<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_ListDevicesRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_ListDevicesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_ListDevicesResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_ListDevicesResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_GetDeviceRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_GetDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_GetDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func getDevice<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_GetDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_GetDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_GetDeviceResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_GetDeviceResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "edgeorchestra.v1.DeviceRegistry" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Register" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_RegisterRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_RegisterRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_RegisterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func register<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_RegisterRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_RegisterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_RegisterResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_RegisterResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Edgeorchestra_V1_DeviceRegistry.Method.Register.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "Unregister" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_UnregisterRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_UnregisterRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_UnregisterResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func unregister<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_UnregisterRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_UnregisterRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_UnregisterResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UnregisterResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Edgeorchestra_V1_DeviceRegistry.Method.Unregister.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "ListDevices" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_ListDevicesRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_ListDevicesRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_ListDevicesResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func listDevices<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_ListDevicesRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_ListDevicesRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_ListDevicesResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_ListDevicesResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Edgeorchestra_V1_DeviceRegistry.Method.ListDevices.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "GetDevice" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_GetDeviceRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_GetDeviceRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_GetDeviceResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func getDevice<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_GetDeviceRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_GetDeviceRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_GetDeviceResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_GetDeviceResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Edgeorchestra_V1_DeviceRegistry.Method.GetDevice.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_DeviceRegistry.ClientProtocol {
    /// Call the "Register" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edgeorchestra_V1_RegisterRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func register<Result>(
        request: GRPCCore.ClientRequest<Edgeorchestra_V1_RegisterRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_RegisterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.register(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_RegisterRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_RegisterResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Unregister" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edgeorchestra_V1_UnregisterRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unregister<Result>(
        request: GRPCCore.ClientRequest<Edgeorchestra_V1_UnregisterRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UnregisterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.unregister(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_UnregisterRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_UnregisterResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListDevices" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edgeorchestra_V1_ListDevicesRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listDevices<Result>(
        request: GRPCCore.ClientRequest<Edgeorchestra_V1_ListDevicesRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_ListDevicesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.listDevices(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_ListDevicesRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_ListDevicesResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDevice" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edgeorchestra_V1_GetDeviceRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getDevice<Result>(
        request: GRPCCore.ClientRequest<Edgeorchestra_V1_GetDeviceRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_GetDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.getDevice(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_GetDeviceRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_GetDeviceResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_DeviceRegistry.ClientProtocol {
    /// Call the "Register" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func register<Result>(
        _ message: Edgeorchestra_V1_RegisterRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_RegisterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edgeorchestra_V1_RegisterRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.register(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "Unregister" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func unregister<Result>(
        _ message: Edgeorchestra_V1_UnregisterRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UnregisterResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edgeorchestra_V1_UnregisterRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.unregister(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "ListDevices" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func listDevices<Result>(
        _ message: Edgeorchestra_V1_ListDevicesRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_ListDevicesResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edgeorchestra_V1_ListDevicesRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.listDevices(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "GetDevice" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func getDevice<Result>(
        _ message: Edgeorchestra_V1_GetDeviceRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_GetDeviceResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edgeorchestra_V1_GetDeviceRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.getDevice(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}