// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: edgeorchestra/v1/heartbeat.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - edgeorchestra.v1.HeartbeatService

/// Namespace containing generated types for the "edgeorchestra.v1.HeartbeatService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Edgeorchestra_V1_HeartbeatService: Sendable {
    /// Service descriptor for the "edgeorchestra.v1.HeartbeatService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.HeartbeatService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "Heartbeat" metadata.
        public enum Heartbeat: Sendable {
            /// Request type for "Heartbeat".
            public typealias Input = Edgeorchestra_V1_HeartbeatRequest
            /// Response type for "Heartbeat".
            public typealias Output = Edgeorchestra_V1_HeartbeatResponse
            /// Descriptor for "Heartbeat".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.HeartbeatService"),
                method: "Heartbeat"
            )
        }
        /// Descriptors for all methods in the "edgeorchestra.v1.HeartbeatService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            Heartbeat.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "edgeorchestra.v1.HeartbeatService" service.
    public static let edgeorchestra_v1_HeartbeatService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.HeartbeatService")
}

// MARK: edgeorchestra.v1.HeartbeatService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_HeartbeatService {
    /// Generated client protocol for the "edgeorchestra.v1.HeartbeatService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "Heartbeat" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Edgeorchestra_V1_HeartbeatRequest` messages.
        ///   - serializer: A serializer for `Edgeorchestra_V1_HeartbeatRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_HeartbeatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func heartbeat<Result>(
            request: GRPCCore.StreamingClientRequest<Edgeorchestra_V1_HeartbeatRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_HeartbeatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_HeartbeatResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_HeartbeatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "edgeorchestra.v1.HeartbeatService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "Heartbeat" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Edgeorchestra_V1_HeartbeatRequest` messages.
        ///   - serializer: A serializer for `Edgeorchestra_V1_HeartbeatRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_HeartbeatResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func heartbeat<Result>(
            request: GRPCCore.StreamingClientRequest<Edgeorchestra_V1_HeartbeatRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_HeartbeatRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_HeartbeatResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_HeartbeatResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.bidirectionalStreaming(
                request: request,
                descriptor: Edgeorchestra_V1_HeartbeatService.Method.Heartbeat.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_HeartbeatService.ClientProtocol {
    /// Call the "Heartbeat" method.
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Edgeorchestra_V1_HeartbeatRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func heartbeat<Result>(
        request: GRPCCore.StreamingClientRequest<Edgeorchestra_V1_HeartbeatRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_HeartbeatResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.heartbeat(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_HeartbeatRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_HeartbeatResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_HeartbeatService.ClientProtocol {
    /// Call the "Heartbeat" method.
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func heartbeat<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Edgeorchestra_V1_HeartbeatRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_HeartbeatResponse>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Edgeorchestra_V1_HeartbeatRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.heartbeat(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}