// DO NOT EDIT.
// swift-format-ignore-file
// swiftlint:disable all
//
// Generated by the gRPC Swift generator plugin for the protocol buffer compiler.
// Source: edgeorchestra/v1/model.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/grpc/grpc-swift

import GRPCCore
import GRPCProtobuf

// MARK: - edgeorchestra.v1.ModelService

/// Namespace containing generated types for the "edgeorchestra.v1.ModelService" service.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
public enum Edgeorchestra_V1_ModelService: Sendable {
    /// Service descriptor for the "edgeorchestra.v1.ModelService" service.
    public static let descriptor = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.ModelService")
    /// Namespace for method metadata.
    public enum Method: Sendable {
        /// Namespace for "UploadModel" metadata.
        public enum UploadModel: Sendable {
            /// Request type for "UploadModel".
            public typealias Input = Edgeorchestra_V1_UploadModelRequest
            /// Response type for "UploadModel".
            public typealias Output = Edgeorchestra_V1_UploadModelResponse
            /// Descriptor for "UploadModel".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.ModelService"),
                method: "UploadModel"
            )
        }
        /// Namespace for "DownloadModel" metadata.
        public enum DownloadModel: Sendable {
            /// Request type for "DownloadModel".
            public typealias Input = Edgeorchestra_V1_DownloadModelRequest
            /// Response type for "DownloadModel".
            public typealias Output = Edgeorchestra_V1_DownloadModelChunk
            /// Descriptor for "DownloadModel".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.ModelService"),
                method: "DownloadModel"
            )
        }
        /// Namespace for "SubmitGradients" metadata.
        public enum SubmitGradients: Sendable {
            /// Request type for "SubmitGradients".
            public typealias Input = Edgeorchestra_V1_SubmitGradientsRequest
            /// Response type for "SubmitGradients".
            public typealias Output = Edgeorchestra_V1_SubmitGradientsResponse
            /// Descriptor for "SubmitGradients".
            public static let descriptor = GRPCCore.MethodDescriptor(
                service: GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.ModelService"),
                method: "SubmitGradients"
            )
        }
        /// Descriptors for all methods in the "edgeorchestra.v1.ModelService" service.
        public static let descriptors: [GRPCCore.MethodDescriptor] = [
            UploadModel.descriptor,
            DownloadModel.descriptor,
            SubmitGradients.descriptor
        ]
    }
}

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension GRPCCore.ServiceDescriptor {
    /// Service descriptor for the "edgeorchestra.v1.ModelService" service.
    public static let edgeorchestra_v1_ModelService = GRPCCore.ServiceDescriptor(fullyQualifiedService: "edgeorchestra.v1.ModelService")
}

// MARK: edgeorchestra.v1.ModelService (client)

@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_ModelService {
    /// Generated client protocol for the "edgeorchestra.v1.ModelService" service.
    ///
    /// You don't need to implement this protocol directly, use the generated
    /// implementation, ``Client``.
    public protocol ClientProtocol: Sendable {
        /// Call the "UploadModel" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Edgeorchestra_V1_UploadModelRequest` messages.
        ///   - serializer: A serializer for `Edgeorchestra_V1_UploadModelRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_UploadModelResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func uploadModel<Result>(
            request: GRPCCore.StreamingClientRequest<Edgeorchestra_V1_UploadModelRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_UploadModelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_UploadModelResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UploadModelResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "DownloadModel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_DownloadModelRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_DownloadModelRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_DownloadModelChunk` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func downloadModel<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_DownloadModelRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_DownloadModelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_DownloadModelChunk>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_DownloadModelChunk>) async throws -> Result
        ) async throws -> Result where Result: Sendable

        /// Call the "SubmitGradients" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_SubmitGradientsRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_SubmitGradientsRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_SubmitGradientsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        func submitGradients<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_SubmitGradientsRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_SubmitGradientsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_SubmitGradientsResponse>,
            options: GRPCCore.CallOptions,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_SubmitGradientsResponse>) async throws -> Result
        ) async throws -> Result where Result: Sendable
    }

    /// Generated client for the "edgeorchestra.v1.ModelService" service.
    ///
    /// The ``Client`` provides an implementation of ``ClientProtocol`` which wraps
    /// a `GRPCCore.GRPCCClient`. The underlying `GRPCClient` provides the long-lived
    /// means of communication with the remote peer.
    public struct Client<Transport>: ClientProtocol where Transport: GRPCCore.ClientTransport {
        private let client: GRPCCore.GRPCClient<Transport>

        /// Creates a new client wrapping the provided `GRPCCore.GRPCClient`.
        ///
        /// - Parameters:
        ///   - client: A `GRPCCore.GRPCClient` providing a communication channel to the service.
        public init(wrapping client: GRPCCore.GRPCClient<Transport>) {
            self.client = client
        }

        /// Call the "UploadModel" method.
        ///
        /// - Parameters:
        ///   - request: A streaming request producing `Edgeorchestra_V1_UploadModelRequest` messages.
        ///   - serializer: A serializer for `Edgeorchestra_V1_UploadModelRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_UploadModelResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func uploadModel<Result>(
            request: GRPCCore.StreamingClientRequest<Edgeorchestra_V1_UploadModelRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_UploadModelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_UploadModelResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UploadModelResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.clientStreaming(
                request: request,
                descriptor: Edgeorchestra_V1_ModelService.Method.UploadModel.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "DownloadModel" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_DownloadModelRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_DownloadModelRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_DownloadModelChunk` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func downloadModel<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_DownloadModelRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_DownloadModelRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_DownloadModelChunk>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_DownloadModelChunk>) async throws -> Result
        ) async throws -> Result where Result: Sendable {
            try await self.client.serverStreaming(
                request: request,
                descriptor: Edgeorchestra_V1_ModelService.Method.DownloadModel.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }

        /// Call the "SubmitGradients" method.
        ///
        /// - Parameters:
        ///   - request: A request containing a single `Edgeorchestra_V1_SubmitGradientsRequest` message.
        ///   - serializer: A serializer for `Edgeorchestra_V1_SubmitGradientsRequest` messages.
        ///   - deserializer: A deserializer for `Edgeorchestra_V1_SubmitGradientsResponse` messages.
        ///   - options: Options to apply to this RPC.
        ///   - handleResponse: A closure which handles the response, the result of which is
        ///       returned to the caller. Returning from the closure will cancel the RPC if it
        ///       hasn't already finished.
        /// - Returns: The result of `handleResponse`.
        public func submitGradients<Result>(
            request: GRPCCore.ClientRequest<Edgeorchestra_V1_SubmitGradientsRequest>,
            serializer: some GRPCCore.MessageSerializer<Edgeorchestra_V1_SubmitGradientsRequest>,
            deserializer: some GRPCCore.MessageDeserializer<Edgeorchestra_V1_SubmitGradientsResponse>,
            options: GRPCCore.CallOptions = .defaults,
            onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_SubmitGradientsResponse>) async throws -> Result = { response in
                try response.message
            }
        ) async throws -> Result where Result: Sendable {
            try await self.client.unary(
                request: request,
                descriptor: Edgeorchestra_V1_ModelService.Method.SubmitGradients.descriptor,
                serializer: serializer,
                deserializer: deserializer,
                options: options,
                onResponse: handleResponse
            )
        }
    }
}

// Helpers providing default arguments to 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_ModelService.ClientProtocol {
    /// Call the "UploadModel" method.
    ///
    /// - Parameters:
    ///   - request: A streaming request producing `Edgeorchestra_V1_UploadModelRequest` messages.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uploadModel<Result>(
        request: GRPCCore.StreamingClientRequest<Edgeorchestra_V1_UploadModelRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UploadModelResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.uploadModel(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_UploadModelRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_UploadModelResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DownloadModel" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edgeorchestra_V1_DownloadModelRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func downloadModel<Result>(
        request: GRPCCore.ClientRequest<Edgeorchestra_V1_DownloadModelRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_DownloadModelChunk>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        try await self.downloadModel(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_DownloadModelRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_DownloadModelChunk>(),
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubmitGradients" method.
    ///
    /// - Parameters:
    ///   - request: A request containing a single `Edgeorchestra_V1_SubmitGradientsRequest` message.
    ///   - options: Options to apply to this RPC.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func submitGradients<Result>(
        request: GRPCCore.ClientRequest<Edgeorchestra_V1_SubmitGradientsRequest>,
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_SubmitGradientsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        try await self.submitGradients(
            request: request,
            serializer: GRPCProtobuf.ProtobufSerializer<Edgeorchestra_V1_SubmitGradientsRequest>(),
            deserializer: GRPCProtobuf.ProtobufDeserializer<Edgeorchestra_V1_SubmitGradientsResponse>(),
            options: options,
            onResponse: handleResponse
        )
    }
}

// Helpers providing sugared APIs for 'ClientProtocol' methods.
@available(macOS 15.0, iOS 18.0, watchOS 11.0, tvOS 18.0, visionOS 2.0, *)
extension Edgeorchestra_V1_ModelService.ClientProtocol {
    /// Call the "UploadModel" method.
    ///
    /// - Parameters:
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - producer: A closure producing request messages to send to the server. The request
    ///       stream is closed when the closure returns.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func uploadModel<Result>(
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        requestProducer producer: @Sendable @escaping (GRPCCore.RPCWriter<Edgeorchestra_V1_UploadModelRequest>) async throws -> Void,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_UploadModelResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.StreamingClientRequest<Edgeorchestra_V1_UploadModelRequest>(
            metadata: metadata,
            producer: producer
        )
        return try await self.uploadModel(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "DownloadModel" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func downloadModel<Result>(
        _ message: Edgeorchestra_V1_DownloadModelRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.StreamingClientResponse<Edgeorchestra_V1_DownloadModelChunk>) async throws -> Result
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edgeorchestra_V1_DownloadModelRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.downloadModel(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }

    /// Call the "SubmitGradients" method.
    ///
    /// - Parameters:
    ///   - message: request message to send.
    ///   - metadata: Additional metadata to send, defaults to empty.
    ///   - options: Options to apply to this RPC, defaults to `.defaults`.
    ///   - handleResponse: A closure which handles the response, the result of which is
    ///       returned to the caller. Returning from the closure will cancel the RPC if it
    ///       hasn't already finished.
    /// - Returns: The result of `handleResponse`.
    public func submitGradients<Result>(
        _ message: Edgeorchestra_V1_SubmitGradientsRequest,
        metadata: GRPCCore.Metadata = [:],
        options: GRPCCore.CallOptions = .defaults,
        onResponse handleResponse: @Sendable @escaping (GRPCCore.ClientResponse<Edgeorchestra_V1_SubmitGradientsResponse>) async throws -> Result = { response in
            try response.message
        }
    ) async throws -> Result where Result: Sendable {
        let request = GRPCCore.ClientRequest<Edgeorchestra_V1_SubmitGradientsRequest>(
            message: message,
            metadata: metadata
        )
        return try await self.submitGradients(
            request: request,
            options: options,
            onResponse: handleResponse
        )
    }
}